kafka:
  clusters:
    -
      name: local
      bootstrapServers: broker:29091
      schemaRegistry: http://schemaregistry:8085
      schemaRegistryAuth:
        username: username
        password: password
      #     schemaNameTemplate: "%s-value"
      metrics:
        port: 9997
        type: JMX